routes/web.php
<?php

Route::get('test','Controller@test');

Route::group(['middleware' => 'CheckLogin'],function(){
	Route::group(['prefix' => 'lop', 'as' => 'lop.'],function(){
		Route::get('','LopController@view_all')->name('view_all');
		Route::get('view_insert','LopController@view_insert')->name('view_insert');
		Route::post('process_insert','LopController@process_insert')->name('process_insert');


		Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
		Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
		Route::get('delete/{ma}','LopController@delete')->name('delete');
	});


	Route::group(['prefix' => 'sinh_vien', 'as' => 'sinh_vien.'],function(){
		Route::get('','SinhVienController@view_all')->name('view_all');
		Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
		Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');


		Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
	});
});

Route::get('login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::get('logout','Controller@logout')->name('logout');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

use Illuminate\Http\Request;
use App\Http\Model\AdminModel;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    public function test()
    {
    	return view('layer.master');
    }
    public function login()
    {
    	return view('login');
    }
    public function process_login(Request $rq)
    {
		$admin           = new AdminModel();
		$admin->email    = $rq->get('email');
		$admin->mat_khau = $rq->get('mat_khau');
		$array           = $admin->get_one();

		if(count($array)==1){
			$rq->session()->put('ma',$array[0]->ma);
			$rq->session()->put('ten',$array[0]->ten);

			return redirect()->route('lop.view_all');
		}
		else{
			return redirect()->route('view_login')->with('error','Nhập sai rồi');
		}
    }
    public function logout(Request $rq)
    {
    	$rq->session()->flush();
		return redirect()->route('view_login')->with('success','Đăng xuất thành công');
    }
}

app/Http/Controllers/LopController.php
<?php 

namespace App\Http\Controllers;

use App\Http\Model\LopModel;
use Illuminate\Http\Request;

class LopController
{
	function view_all(){
		$array = LopModel::get_all();

		return view('lop.view_all',compact('array'));
	}
	function view_insert(){
		return view('lop.view_insert');
	}
	function process_insert(Request $rq){
		$lop = new LopModel();
		$lop->ten = $rq->get('ten');
		$lop->insert();

		// return redirect()->route("lop.view_all");
	}
	function view_update($ma)
	{
		$each = LopModel::get_one($ma);

		return view('lop.view_update',compact('each'));
	}
	function process_update($ma, Request $rq)
	{
		$lop = new LopModel();
		$lop->ma = $ma;
		$lop->ten = $rq->get('ten');
		$lop->update();

		// return redirect()->route("lop.view_all");
	}
	function delete($ma){
		LopModel::delete($ma);

		// return redirect()->route("lop.view_all");
	}
}

app/Http/Controllers/SinhVienController.php
<?php 

namespace App\Http\Controllers;

use App\Http\Model\LopModel;
use App\Http\Model\SinhVienModel;
use Illuminate\Http\Request;

class SinhVienController
{
	function view_all(){
		$array = SinhVienModel::get_all();

		return view('sinh_vien.view_all',compact('array'));
	}
	function view_insert(){
		$array_lop = LopModel::get_all();

		return view('sinh_vien.view_insert',compact('array_lop'));
	}
	function process_insert(Request $rq){
		$sinh_vien = new SinhVienModel();
		$sinh_vien->ten = $rq->get('ten');
		$sinh_vien->tuoi = $rq->get('tuoi');
		$sinh_vien->ma_lop = $rq->get('ma_lop');
		$sinh_vien->insert();

		// return redirect()->route("sinh_vien.view_all");
	}
	function view_update($ma)
	{
		$each = SinhVienModel::get_one($ma);
		$array_lop = LopModel::get_all();

		return view('sinh_vien.view_update',compact('each','array_lop'));
	}
	function process_update($ma, Request $rq)
	{
		$sinh_vien = new SinhVienModel();
		$sinh_vien->ma = $ma;
		$sinh_vien->ten = $rq->get('ten');
		$sinh_vien->tuoi = $rq->get('tuoi');
		$sinh_vien->ma_lop = $rq->get('ma_lop');
		$sinh_vien->update();

		return redirect()->route("sinh_vien.view_all");
	}
	function delete($ma){
		SinhVienModel::delete($ma);

		// return redirect()->route("sinh_vien.view_all");
	}
}

resources/views/layer/footer.blade.php
 <footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">
                        Company
                    </a>
                </li>
                <li>
                    <a href="#">
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                       Blog
                    </a>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
        </p>
    </div>
</footer>

resources/views/layer/header.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
		<div class="navbar-minimize">
			<button id="minimizeSidebar" class="btn btn-warning btn-fill btn-round btn-icon">
				<i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
				<i class="fa fa-navicon visible-on-sidebar-mini"></i>
			</button>
		</div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Calendar</a>
        </div>
        <div class="collapse navbar-collapse">

            <form class="navbar-form navbar-left navbar-search-form" role="search">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" value="" class="form-control" placeholder="Search...">
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="charts.html">
                        <i class="fa fa-line-chart"></i>
                        <p>Stats</p>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-gavel"></i>
                        <p class="hidden-md hidden-lg">
                            Actions
                            <b class="caret"></b>
                        </p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Create New Post</a></li>
                        <li><a href="#">Manage Something</a></li>
                        <li><a href="#">Do Nothing</a></li>
                        <li><a href="#">Submit to live</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Another Action</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="notification">5</span>
                        <p class="hidden-md hidden-lg">
							Notifications
							<b class="caret"></b>
						</p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Notification 1</a></li>
                        <li><a href="#">Notification 2</a></li>
                        <li><a href="#">Notification 3</a></li>
                        <li><a href="#">Notification 4</a></li>
                        <li><a href="#">Another notification</a></li>
                    </ul>
                </li>

                <li class="dropdown dropdown-with-icons">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-list"></i>
                        <p class="hidden-md hidden-lg">
							More
							<b class="caret"></b>
						</p>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="#">
                                <i class="pe-7s-mail"></i> Messages
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-help1"></i> Help Center
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-tools"></i> Settings
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-lock"></i> Lock Screen
                            </a>
                        </li>
                        <li>
                            <a href="#" class="text-danger">
                                <i class="pe-7s-close-circle"></i>
                                Log out
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>

resources/views/layer/master.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard PRO by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" />

    <!--  Light Bootstrap Dashboard core CSS    -->
    <link href="{{ asset('css/light-bootstrap-dashboard.css') }}" rel="stylesheet"/>



    <!--     Fonts and icons     -->
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href='{{ asset('css/font.css') }}' rel='stylesheet' type='text/css'>

</head>
<body>

<div class="wrapper">
	@include('layer.menu')
        <!--

            Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
            Tip 2: you can also add an image using data-image tag

        -->

        

    <div class="main-panel">
        @include('layer.header')


        <div class="main-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">

                        <div class="card card-calendar">
                            <div class="content">
                               @yield('body')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

       @include('layer.footer')


    </div>
</div>


</body>
    <!--   Core JS Files  -->
    <script src="{{ asset('js/jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/light-bootstrap-dashboard.js') }}" type="text/javascript"></script>


</html>

resources/views/layer/menu.blade.php
<div class="sidebar" data-color="orange">	
	<div class="logo">
	    <a href="http://www.creative-tim.com" class="simple-text logo-mini">
	        Ct
	    </a>

		<a href="http://www.creative-tim.com" class="simple-text logo-normal">
			Creative Tim
		</a>
	</div>
	<div class="sidebar-wrapper">
        <div class="user">
			<div class="info">
				<div class="photo">
                    <img src="../assets/img/default-avatar.png" />
                </div>

				<a data-toggle="collapse" href="#collapseExample" class="collapsed">
					<span>
						Tania Andrew
                        <b class="caret"></b>
					</span>
                </a>

				<div class="collapse" id="collapseExample">
					<ul class="nav">
						<li>
							<a href="#pablo">
								<span class="sidebar-mini">MP</span>
								<span class="sidebar-normal">My Profile</span>
							</a>
						</li>

						<li>
							<a href="#pablo">
								<span class="sidebar-mini">EP</span>
								<span class="sidebar-normal">Edit Profile</span>
							</a>
						</li>

						<li>
							<a href="#pablo">
								<span class="sidebar-mini">S</span>
								<span class="sidebar-normal">Settings</span>
							</a>
						</li>
					</ul>
                </div>
			</div>
        </div>

		<ul class="nav">
			<li>
				<a href="dashboard.html">
					<i class="pe-7s-graph"></i>
					<p>Dashboard</p>
				</a>
			</li>
			<li>
				<a data-toggle="collapse" href="#componentsExamples">
                    <i class="pe-7s-plugin"></i>
                    <p>Components
                       <b class="caret"></b>
                    </p>
                </a>
				<div class="collapse" id="componentsExamples">
					<ul class="nav">
						<li>
							<a href="components/buttons.html">
								<span class="sidebar-mini">B</span>
								<span class="sidebar-normal">Buttons</span>
							</a>
						</li>
						<li>
							<a href="components/grid.html">
								<span class="sidebar-mini">GS</span>
								<span class="sidebar-normal">Grid System</span>
							</a>
						</li>
						<li>
							<a href="components/panels.html">
								<span class="sidebar-mini">P</span>
								<span class="sidebar-normal">Panels</span>
							</a>
						</li>
						<li>
							<a href="components/sweet-alert.html">
								<span class="sidebar-mini">SA</span>
								<span class="sidebar-normal">Sweet Alert</span>
							</a>
						</li>
						<li>
							<a href="components/notifications.html">
								<span class="sidebar-mini">N</span>
								<span class="sidebar-normal">Notifications</span>
							</a>
						</li>
						<li>
							<a href="components/icons.html">
								<span class="sidebar-mini">I</span>
								<span class="sidebar-normal">Icons</span>
							</a>
						</li>
						<li>
							<a href="components/typography.html">
								<span class="sidebar-mini">T</span>
								<span class="sidebar-normal">Typography</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<li>
				<a data-toggle="collapse" href="#formsExamples">
                    <i class="pe-7s-note2"></i>
                    <p>Forms
                       <b class="caret"></b>
                    </p>
                </a>
				<div class="collapse" id="formsExamples">
					<ul class="nav">
						<li>
							<a href="forms/regular.html">
								<span class="sidebar-mini">Rf</span>
								<span class="sidebar-normal">Regular Forms</span>
							</a>
						</li>
						<li>
							<a href="forms/extended.html">
								<span class="sidebar-mini">Ef</span>
								<span class="sidebar-normal">Extended Forms</span>
							</a>
						</li>
						<li>
							<a href="forms/validation.html">
								<span class="sidebar-mini">Vf</span>
								<span class="sidebar-normal">Validation Forms</span>
							</a>
						</li>
						<li>
							<a href="forms/wizard.html">
								<span class="sidebar-mini">W</span>
								<span class="sidebar-normal">Wizard</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<li>
				<a data-toggle="collapse" href="#tablesExamples">
                    <i class="pe-7s-news-paper"></i>
                    <p>Tables
                       <b class="caret"></b>
                    </p>
                </a>
				<div class="collapse" id="tablesExamples">
					<ul class="nav">
						<li>
							<a href="tables/regular.html">
								<span class="sidebar-mini">RT</span>
								<span class="sidebar-normal">Regular Tables</span>
							</a>
						</li>
						<li>
							<a href="tables/extended.html">
								<span class="sidebar-mini">ET</span>
								<span class="sidebar-normal">Extended Tables</span>
							</a>
						</li>
						<li>
							<a href="tables/bootstrap-table.html">
								<span class="sidebar-mini">BT</span>
								<span class="sidebar-normal">Bootstrap Table</span>
							</a>
						</li>
						<li>
							<a href="tables/datatables.net.html">
								<span class="sidebar-mini">DT</span>
								<span class="sidebar-normal">DataTables.net</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<li>
				<a data-toggle="collapse" href="#mapsExamples">
                    <i class="pe-7s-map-marker"></i>
                    <p>Maps
                       <b class="caret"></b>
                    </p>
                </a>
				<div class="collapse" id="mapsExamples">
					<ul class="nav">
						<li>
							<a href="maps/google.html">
								<span class="sidebar-mini">GM</span>
								<span class="sidebar-normal">Google Maps</span>
							</a>
						</li>
						<li>
							<a href="maps/vector.html">
								<span class="sidebar-mini">VM</span>
								<span class="sidebar-normal">Vector maps</span>
							</a>
						</li>
						<li>
							<a href="maps/fullscreen.html">
								<span class="sidebar-mini">FSM</span>
								<span class="sidebar-normal">Full Screen Map</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<li>
                <a href="charts.html">
                    <i class="pe-7s-graph1"></i>
                    <p>Charts</p>
                </a>
            </li>

            <li class="active">
                <a href="calendar.html">
                    <i class="pe-7s-date"></i>
                    <p>Calendar</p>
                </a>
            </li>
			<li>
				<a data-toggle="collapse" href="#pagesExamples">
                    <i class="pe-7s-gift"></i>
                    <p>Pages
                       <b class="caret"></b>
                    </p>
                </a>
				<div class="collapse" id="pagesExamples">
					<ul class="nav">
						<li>
							<a href="pages/user.html">
								<span class="sidebar-mini">UP</span>
								<span class="sidebar-normal">User Page</span>
							</a>
						</li>
						<li>
							<a href="pages/login.html">
								<span class="sidebar-mini">LP</span>
								<span class="sidebar-normal">Login Page</span>
							</a>
						</li>
						<li>
							<a href="pages/register.html">
								<span class="sidebar-mini">RP</span>
								<span class="sidebar-normal">Register Page</span>
							</a>
						</li>
						<li>
							<a href="pages/lock.html">
								<span class="sidebar-mini">LSP</span>
								<span class="sidebar-normal">Lock Screen Page</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>

resources/views/login.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard PRO by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
     <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" />

    <!--  Light Bootstrap Dashboard core CSS    -->
    <link href="{{ asset('css/light-bootstrap-dashboard.css') }}" rel="stylesheet"/>



    <!--     Fonts and icons     -->
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href='{{ asset('css/font.css') }}' rel='stylesheet' type='text/css'>

</head>
<body>



<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" data-color="orange">

    <!--   you can change the color of the filter page using: data-color="blue | azure | green | orange | red | purple" -->
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="post" action="{{ route('process_login') }}">
                        {{csrf_field()}}
                        
                        <!--   if you want to have the card without animation please remove the ".card-hidden" class   -->
                            <div class="card">
                                <div class="header text-center">Login</div>
                                <div class="content">
                                    @if (Session::has('error'))
                                        <h1>{{Session::get('error')}}</h1>
                                    @endif
                                    @if (Session::has('success'))
                                        <h1>{{Session::get('success')}}</h1>
                                    @endif
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <input type="email" name="email" placeholder="Enter email" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" name="mat_khau" placeholder="Password" class="form-control">
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class="btn btn-fill btn-warning btn-wd">Login</button>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


</body>

</html>

resources/views/lop/view_all.blade.php
@extends('layer.master')

@section('body')
<a href="{{ route('lop.view_insert') }}">
	Thêm
</a>
<table class="table">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>{{$each->ma}}</td>
			<td>{{$each->ten}}</td>
			<td>
				<a href="{{ route('lop.view_update',['ma' => $each->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('lop.delete',['ma' => $each->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>
@endsection

resources/views/lop/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('lop.process_insert') }}" method="post">
	{{csrf_field()}}
	Tên
	<input type="text" name="ten">
	<br>
	<button>Thêm</button>
</form>
</body>
</html>

resources/views/lop/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('lop.process_update',['ma' => $each->ma]) }}" method="post">
	{{csrf_field()}}
	Tên
	<input type="text" name="ten" value="{{$each->ten}}">
	<br>
	<button>Sửa</button>
</form>
</body>
</html>

resources/views/sinh_vien/view_all.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<a href="{{ route('sinh_vien.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Tuổi</th>
		<th>Tên Lớp</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>{{$each->ma}}</td>
			<td>{{$each->ten}}</td>
			<td>{{$each->tuoi}}</td>
			<td>{{$each->ten_lop}}</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma' => $each->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.delete',['ma' => $each->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>
</body>
</html>

resources/views/sinh_vien/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('sinh_vien.process_insert') }}" method="post">
	{{csrf_field()}}
	Tên
	<input type="text" name="ten">
	<br>
	Tuổi
	<input type="text" name="tuoi">
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}">
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<br>
	<button>Thêm</button>
</form>
</body>
</html>

resources/views/sinh_vien/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('sinh_vien.process_update',['ma' => $each->ma]) }}" method="post">
	{{csrf_field()}}
	Tên
	<input type="text" name="ten" value="{{$each->ten}}">
	<br>
	Tuổi
	<input type="text" name="tuoi" value="{{$each->tuoi}}">
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{$lop->ma}}" @if($each->ma_lop==$lop->ma) selected @endif>
				{{$lop->ten}}
			</option>
		@endforeach
	</select>
	<br>
	<button>Sửa</button>
</form>
</body>
</html>